# E2E bake acceptance template, migrated to the
# cloud-hypervisor builder.
#
# Boots a pinned Ubuntu 24.04 cloud image (systemd 255 >= the 255 floor and
# the 252/254 confext/sysext floors) under the cloud-hypervisor builder
# (firmware/EDK2 boot), applies the sysext and confext provisioners in bake
# mode, then runs test/e2e/bake/assert.sh in the guest to verify the
# following semantics:
#   - extension files exist at their merged /usr and /etc paths
#   - /var/lib/extensions and /var/lib/confexts are empty (bake removes them)
#   - baked extension-release.d files are absent
#
# Networking: the plugin derives the SSH target from the network interface's
# `ip` field (builder CommHost), so the guest is given the static address
# 10.0.2.2/24 via a cloud-init NoCloud seed ISO generated by run.sh; run.sh
# assigns the host side of TAP ch-tap-0 the gateway address 10.0.2.1/24.
# The interface `ip` is the plain guest address (the cloud-hypervisor API
# deserializes net[].ip as IpAddr, so CIDR syntax like 10.0.2.2/24 is
# rejected) and `mask` the dotted-quad netmask (CH rejects an ip without a
# mask at vm.boot). For a TAP that already carries an address
# cloud-hypervisor preserves the existing host-side IP, so the interface `ip`
# here is effectively used as the SSH host only.
# Authentication is ephemeral-publickey-based (run.sh generates
# .out/e2e-ssh-key; the seed's bootcmd installs the public half and re-ids
# ubuntu to uid 0 (usermod -o -u 0 / useradd -o -u 0) so the
# provisioner root preflight passes - the packer SSH communicator
# has no sudo wrapper. Password auth is not used (see the communicator block).
#
# See test/e2e/bake/README.md for the pinned assets, host prerequisites, and
# how to run/skip this acceptance suite.

variable "firmware_path" {
  type        = string
  description = "Path to the EDK2 CLOUDHV.fd firmware fetched by run.sh (default: .out/CLOUDHV.fd)."
  default     = ""
}

variable "disk_path" {
  type        = string
  description = "Path to the raw Ubuntu 24.04 cloud image converted by run.sh (default: .out/ubuntu-24.04-server-cloudimg-amd64.raw)."
  default     = ""
}

variable "seed_iso_path" {
  type        = string
  description = "Path to the cloud-init NoCloud seed ISO generated by run.sh (default: .out/seed.iso)."
  default     = ""
}

variable "ch_binary" {
  type        = string
  description = "cloud-hypervisor binary name or path (mirrors the plugin's firmware-boot example)."
  default     = "cloud-hypervisor"
}

variable "guest_ip" {
  type        = string
  description = "Static guest IP (plain address, no CIDR suffix), used by the cloud-hypervisor plugin as the SSH host (CommHost)."
  default     = "10.0.2.2"
}

variable "guest_mask" {
  type        = string
  description = "Static guest netmask (dotted quad); the cloud-hypervisor API rejects an ip without a mask at vm.boot."
  default     = "255.255.255.0"
}

variable "dissect_binary" {
  type        = string
  description = "Path to the guest systemd-dissect binary extracted by run.sh from the pinned Ubuntu systemd-container .deb (default: .out/systemd-dissect)."
  default     = ""
}

variable "ssh_private_key" {
  type        = string
  description = "Path to the ephemeral SSH private key generated by run.sh for guest auth (default: .out/e2e-ssh-key)."
  default     = ""
}

variable "vcpus" {
  type        = number
  description = "Number of virtual CPUs for the guest."
  default     = 2
}

variable "memory" {
  type        = number
  description = "Memory in MiB for the guest."
  default     = 2048
}

# Asset paths default under .out/ (generated by run.sh, gitignored); path.root
# cannot appear in variable defaults, so the effective paths are resolved here.
locals {
  firmware_path  = var.firmware_path == "" ? "${path.root}/.out/CLOUDHV.fd" : var.firmware_path
  disk_path      = var.disk_path == "" ? "${path.root}/.out/ubuntu-24.04-server-cloudimg-amd64.raw" : var.disk_path
  seed_iso_path  = var.seed_iso_path == "" ? "${path.root}/.out/seed.iso" : var.seed_iso_path
  dissect_binary = var.dissect_binary == "" ? "${path.root}/.out/systemd-dissect" : var.dissect_binary
  ssh_key        = var.ssh_private_key == "" ? "${path.root}/.out/e2e-ssh-key" : var.ssh_private_key
}

source "cloud-hypervisor" "bake" {
  # Explicit, like the plugin's firmware-boot example: the builder's
  # pre-decode default is wiped during HCL2 decode, so the key must be set.
  ch_binary_path = var.ch_binary

  vcpus  = var.vcpus
  memory = var.memory

  # UEFI firmware boot (EDK2 CLOUDHV.fd) instead of a direct kernel.
  firmware = local.firmware_path

  # Boot disk: the pinned Ubuntu 24.04 cloud image converted to raw by run.sh
  # (qcow2 -> raw). Writable so the build captures it as artifact.
  disk_images {
    path       = local.disk_path
    readonly   = false
    image_type = "raw"
  }

  # cloud-init NoCloud seed (generated by run.sh from .out/seed/): static
  # network config + user data. Read-only: not part of the captured artifact.
  disk_images {
    path       = local.seed_iso_path
    readonly   = true
    image_type = "raw"
  }

  # TAP device bridged to the host (the literal is tap = "ch-tap-0",
  # created by run.sh). `ip` is the guest's static address (plain, no CIDR
  # suffix) and the SSH host per CommHost: the cloud-hypervisor API
  # deserializes net[].ip as IpAddr, so a CIDR value like 10.0.2.2/24 in `ip`
  # is rejected. run.sh pre-assigns the host side of the TAP the gateway
  # (10.0.2.1/24); cloud-hypervisor preserves an existing TAP's address.
  network_interfaces {
    tap = "ch-tap-0"
    ip  = var.guest_ip
    # The cloud-hypervisor API rejects an ip without a mask at vm.boot.
    mask = var.guest_mask
  }

  communicator = "ssh"
  ssh_username = "ubuntu"
  # Ephemeral key auth: run.sh generates .out/e2e-ssh-key and the seed's
  # bootcmd installs the matching public key. Password auth is not used: the
  # stock Ubuntu 24.04 cloud image rejects password logins even with a
  # correctly hashed password (PAM failure on a fresh first boot), while
  # publickey auth works (verified in the harness E2E).
  ssh_private_key_file = local.ssh_key
  ssh_timeout          = "20m"

  # SSH-only interaction; no serial/console output needed.
  serial  = "null"
  console = "null"
}

build {
  sources = ["source.cloud-hypervisor.bake"]

  # The prebuilt-.raw bake flow runs `systemd-dissect --copy-from`
  # inside the guest, but the base Ubuntu 24.04 cloud image ships
  # systemd-dissect only as a bash-completion stub (the binary is in the
  # systemd-container package). run.sh extracts the binary from the pinned
  # systemd-container .deb; this provisioner uploads it into the guest before
  # any extension provisioner runs. The SSH session is uid 0 (the seed re-ids
  # ubuntu), so /usr/bin is writable.
  provisioner "file" {
    source      = local.dissect_binary
    destination = "/usr/bin/systemd-dissect"
  }

  # System extension merged over /usr and baked into the rootfs.
  # Entry (a): directory source. fixtures/sysext-src/bin/sysext-hello is
  # wrapped as usr/bin/sysext-hello inside the extension and must land at
  # /usr/bin/sysext-hello. The release file is auto-generated from the guest's
  # os-release.
  # NOTE: the label is namespaced as <accessor>-<name> because packer 1.11.x
  # registers a multi-component plugin's literal-name provisioners under
  # "systemd-ext-sysext"/"systemd-ext-confext".
  provisioner "systemd-ext-sysext" {
    mode = "bake"
    extensions {
      name   = "sysext-dir"
      source = "${path.root}/fixtures/sysext-src"
    }
    # Entry (b): prebuilt squashfs .raw generated by run.sh
    # (test/e2e/bake/.out/prebuilt/sysext-raw.raw). It is uploaded as-is and
    # baked via systemd-dissect --copy-from. The image must carry
    # its own matching release file; run.sh writes one with
    # ID/VERSION_ID matching the pinned guest.
    extensions {
      name   = "sysext-raw"
      source = "${path.root}/.out/prebuilt/sysext-raw.raw"
    }
  }

  # Configuration extension merged over /etc and baked into the rootfs.
  # fixtures/confext-src/e2e-conf/main.conf must land at
  # /etc/e2e-conf/main.conf.
  provisioner "systemd-ext-confext" {
    mode = "bake"
    extensions {
      name   = "e2e-conf"
      source = "${path.root}/fixtures/confext-src"
    }
  }

  # Guest-side assertions (see assert.sh for the check list).
  provisioner "shell" {
    script = "${path.root}/assert.sh"
  }
}
