// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package confext

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName     *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType   *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion   *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug         *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce         *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError       *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars      map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	Extensions          []FlatExtension   `mapstructure:"extensions" cty:"extensions" hcl:"extensions"`
	Mode                *string           `mapstructure:"mode" cty:"mode" hcl:"mode"`
	MergeDuringBuild    *bool             `mapstructure:"merge_during_build" cty:"merge_during_build" hcl:"merge_during_build"`
	Command             *string           `mapstructure:"command" cty:"command" hcl:"command"`
	GuestInstallDir     *string           `mapstructure:"guest_install_dir" cty:"guest_install_dir" hcl:"guest_install_dir"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"extensions":                 &hcldec.BlockListSpec{TypeName: "extensions", Nested: hcldec.ObjectSpec((*FlatExtension)(nil).HCL2Spec())},
		"mode":                       &hcldec.AttrSpec{Name: "mode", Type: cty.String, Required: false},
		"merge_during_build":         &hcldec.AttrSpec{Name: "merge_during_build", Type: cty.Bool, Required: false},
		"command":                    &hcldec.AttrSpec{Name: "command", Type: cty.String, Required: false},
		"guest_install_dir":          &hcldec.AttrSpec{Name: "guest_install_dir", Type: cty.String, Required: false},
	}
	return s
}

// FlatExtension is an auto-generated flat version of Extension.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatExtension struct {
	Name        *string `mapstructure:"name" cty:"name" hcl:"name"`
	Source      *string `mapstructure:"source" cty:"source" hcl:"source"`
	Format      *string `mapstructure:"format" cty:"format" hcl:"format"`
	ReleaseFile *string `mapstructure:"release_file" cty:"release_file" hcl:"release_file"`
}

// FlatMapstructure returns a new FlatExtension.
// FlatExtension is an auto-generated flat version of Extension.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Extension) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatExtension)
}

// HCL2Spec returns the hcl spec of a Extension.
// This spec is used by HCL to read the fields of Extension.
// The decoded values from this spec will then be applied to a FlatExtension.
func (*FlatExtension) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"name":         &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"source":       &hcldec.AttrSpec{Name: "source", Type: cty.String, Required: false},
		"format":       &hcldec.AttrSpec{Name: "format", Type: cty.String, Required: false},
		"release_file": &hcldec.AttrSpec{Name: "release_file", Type: cty.String, Required: false},
	}
	return s
}
