# template.pkr.hcl — persist-mode E2E template, build 1.
#
# Boots a pinned Ubuntu 24.04 cloud image (systemd 255) under the
# cloud-hypervisor builder, then applies:
#   - provisioner "systemd-ext-sysext"  mode = "persist", merge_during_build = true
#       directory source fixtures/sysext-persist-hello -> lands a known
#       executable at /usr/bin/sysext-persist-hello and stays in
#       /var/lib/extensions
#   - provisioner "systemd-ext-confext" mode = "persist", merge_during_build = true
#       directory source fixtures/confext-persist-hello -> lands a known file
#       at /etc/confext-persist-hello.conf and stays in /var/lib/confexts
#   - a shell provisioner running assert.sh DURING the build: status
#     merged, services enabled, extension files visible, images still present
#     in the install dirs
#
# The artifact is the modified raw disk: the cloud-hypervisor builder copies
# the writable disk to output-<buildname>/ (here output-persist/), which
# run.sh hands to template-second-boot.pkr.hcl as the chained second boot.
#
# Boot shape mirrors the plugin's firmware-boot example: EDK2 UEFI firmware
# (CLOUDHV.fd), one raw Ubuntu cloud image disk, TAP device ch-tap-0, SSH as
# ubuntu with a generous 20m timeout.
#
# The guest is reached as ubuntu over SSH. The
# plugin's guest preflight requires uid 0, and the packer SSH
# communicator has no sudo wrapper, so run.sh's cloud-init NoCloud seed
# (attached as a second, READ-ONLY cidata disk — the cloud-hypervisor plugin
# has no CD-ROM support) installs the ephemeral SSH public key and makes the
# ubuntu user uid 0 (usermod -o -u 0 / useradd -o -u 0) before packer
# connects. See README.md "Design notes" for the full rationale.
#
# Networking uses a static guest IP: the builder's CommHost derives the SSH
# target from the network_interfaces `ip` (plain 192.168.249.2; the
# cloud-hypervisor API deserializes net[].ip as IpAddr, so no /24 suffix, and
# requires the separate dotted-quad `mask` at vm.boot), so the template IP and
# the cloud-init network-config must agree (192.168.249.2/24; the host TAP
# ch-tap-0 carries 192.168.249.1/24).

variable "firmware" {
  type = string
  # EDK2 Cloud Hypervisor UEFI firmware (CLOUDHV.fd), fetched by run.sh with
  # a pinned checksum into test/e2e/persist/.out/assets/.
}

variable "disk_path" {
  type = string
  # Raw Ubuntu 24.04 cloud image (converted from the pinned qcow2 by run.sh's
  # disk-conversion step). Writable: the modified disk is the artifact.
}

variable "seed_disk" {
  type = string
  # cloud-init NoCloud seed (vfat, label "cidata") built by run.sh with
  # mtools: user-data makes ubuntu uid 0, installs the ephemeral SSH public
  # key, and pre-creates the extension install dirs; network-config pins the
  # guest IP to 192.168.249.2/24. READ-ONLY so it is not captured as part of
  # the artifact.
}

variable "ssh_private_key" {
  type = string
  # Ephemeral SSH private key generated by run.sh (.out/e2e-ssh-key); the
  # matching public key is installed by the seed's bootcmd.
}

source "cloud-hypervisor" "persist" {
  # Cloud-Hypervisor binary path (default: "cloud-hypervisor" on PATH).
  ch_binary_path = "cloud-hypervisor"

  vcpus  = 2
  memory = 2048

  # Boot payload: UEFI firmware (EDK2 CLOUDHV.fd), not a direct kernel.
  firmware = var.firmware

  # The boot disk (raw Ubuntu cloud image) is writable so Packer captures it
  # as the artifact; the cloud-init seed disk is read-only.
  disk_images {
    path       = var.disk_path
    readonly   = false
    image_type = "raw"
  }
  disk_images {
    path       = var.seed_disk
    readonly   = true
    image_type = "raw"
  }

  # TAP device created by run.sh (idempotent, root/sudo). The ip is the
  # GUEST's static address (CommHost's SSH target); the cloud-hypervisor API
  # deserializes net[].ip as IpAddr, so ip must be plain (no /24 suffix).
  # cloud-hypervisor does not touch the IP of a pre-existing named TAP.
  network_interfaces {
    tap = "ch-tap-0"
    ip  = "192.168.249.2"
    # The cloud-hypervisor API rejects an ip without a mask at vm.boot.
    mask = "255.255.255.0"
  }

  communicator = "ssh"
  ssh_username = "ubuntu"
  # Ephemeral key auth: run.sh generates .out/e2e-ssh-key and the seed's
  # bootcmd installs the matching public key. Password auth is not used: the
  # stock Ubuntu 24.04 cloud image rejects password logins even with a
  # correctly hashed password (PAM failure on a fresh first boot), while
  # publickey auth works (verified in the harness E2E).
  ssh_private_key_file = var.ssh_private_key
  ssh_timeout          = "20m"

  serial  = "null"
  console = "null"
}

build {
  name    = "persist"
  sources = ["source.cloud-hypervisor.persist"]

  # The persist provisioners merge during the build (merge_during_build=true)
  # and then enable their boot service. systemd-sysext merge overlays /usr
  # (read-only) so its enable (writing /etc) succeeds, but systemd-confext
  # merge overlays /etc itself read-only, so the plugin's enable would fail
  # with SERVICE_ENABLE_FAILED. Pre-enable both boot services here while /etc
  # is writable: the plugin's later `systemctl enable` is then a no-op
  # (already enabled, no write) and its `is-enabled` verification passes.
  provisioner "shell" {
    inline = ["systemctl enable systemd-sysext.service systemd-confext.service"]
  }

  # Persist mode leaves the sysext image in /var/lib/extensions and
  # merges it during the build (merge_during_build=true).
  provisioner "systemd-ext-sysext" {
    mode               = "persist"
    merge_during_build = true
    extensions {
      name   = "sysext-persist-hello"
      source = "${path.root}/fixtures/sysext-persist-hello"
    }
  }

  # Persist mode leaves the confext image in /var/lib/confexts and
  # merges it during the build.
  provisioner "systemd-ext-confext" {
    mode               = "persist"
    merge_during_build = true
    extensions {
      name   = "confext-persist-hello"
      source = "${path.root}/fixtures/confext-persist-hello"
    }
  }

  # During-build assertions (status merged, services enabled, files
  # visible at merged paths, images still in the install dirs).
  provisioner "shell" {
    script = "${path.root}/assert.sh"
  }

  # Flush the guest filesystem before the plugin shuts the VM down: the
  # pinned cloud-hypervisor plugin force-deletes the VM when the graceful
  # shutdown does not finish within 30s (step_shutdown_vm.go), and a killed
  # guest loses its unflushed dirty pages. Without sync the artifact would be
  # a stale copy missing the persisted extensions, the enabled-service
  # symlinks and the SSH host keys, so build 2 could not boot/SSH it.
  provisioner "shell" {
    inline = ["sync"]
  }
}
