# template-second-boot.pkr.hcl — chained second boot, build 2.
#
# Boots the ARTIFACT of build 1 (template.pkr.hcl) a second time, from a
# fresh boot, to prove persist mode survives a reboot (the second-boot
# criterion). run.sh passes the artifact path via
# -var artifact_disk; this template has NO extension provisioners — only a
# shell provisioner running assert-second-boot.sh, which verifies after the
# fresh boot that:
#   - systemd-sysext status reports merged (the boot-time
#     systemd-sysext.service / systemd-confext.service re-applied the
#     persisted extensions)
#   - the sysext file is visible at its merged /usr path
#   - the confext file is visible at its merged /etc path
#
# Same firmware/disk/network shape as build 1: EDK2 UEFI firmware, one raw
# disk (the artifact), TAP ch-tap-0, SSH as ubuntu with the ephemeral key,
# 20m timeout. No cloud-init seed is attached: the guest network config, the
# ubuntu user (uid 0), the authorized key and the persisted extensions are
# baked into the artifact by build 1, and cloud-init finds no datasource on
# this boot.

variable "firmware" {
  type = string
  # EDK2 Cloud Hypervisor UEFI firmware (CLOUDHV.fd); same pin as build 1.
}

variable "artifact_disk" {
  type = string
  # The modified raw disk produced by build 1 (resolved by run.sh from
  # output-persist/).
}

variable "ssh_private_key" {
  type = string
  # Ephemeral SSH private key generated by run.sh (.out/e2e-ssh-key); the
  # matching public key was installed into the artifact by build 1.
}

source "cloud-hypervisor" "second-boot" {
  # Cloud-Hypervisor binary path (default: "cloud-hypervisor" on PATH).
  ch_binary_path = "cloud-hypervisor"

  vcpus  = 2
  memory = 2048

  # Boot payload: UEFI firmware (EDK2 CLOUDHV.fd), not a direct kernel.
  firmware = var.firmware

  # The build-1 artifact is writable so the builder can capture it again
  # (the second boot itself must not modify the artifact, but the builder
  # requires a writable disk for artifact collection; the boot is
  # read-only in practice for this harness).
  disk_images {
    path       = var.artifact_disk
    readonly   = false
    image_type = "raw"
  }

  # TAP device created by run.sh (idempotent, root/sudo). The ip is the
  # GUEST's static address (CommHost's SSH target); the cloud-hypervisor API
  # deserializes net[].ip as IpAddr, so ip must be plain (no /24 suffix). It
  # matches the network-config baked into the artifact by build 1.
  network_interfaces {
    tap = "ch-tap-0"
    ip  = "192.168.249.2"
    # The cloud-hypervisor API rejects an ip without a mask at vm.boot.
    mask = "255.255.255.0"
  }

  communicator = "ssh"
  ssh_username = "ubuntu"
  # Ephemeral key auth (the authorized key was baked into the artifact by
  # build 1); password auth is not used (see build 1 template).
  ssh_private_key_file = var.ssh_private_key
  ssh_timeout          = "20m"

  serial  = "null"
  console = "null"
}

build {
  name    = "second-boot"
  sources = ["source.cloud-hypervisor.second-boot"]

  # Second-boot assertions, run after the fresh boot. The script waits
  # for the boot-time merge before asserting, so a spurious NOT MERGED right
  # after SSH comes up cannot fail the build.
  provisioner "shell" {
    script = "${path.root}/assert-second-boot.sh"
  }
}
