// Contract tests for the post-migration E2E harness static contract.
//
// The harnesses under test/e2e/ are still QEMU-based when this file lands
// (the migration moves test/e2e/bake and test/e2e/persist to
// cloud-hypervisor). These assertions therefore FAIL (red) against the
// current tree and must PASS after those tasks: templates become
// `source "cloud-hypervisor"`, persist's second boot becomes
// template-second-boot.pkr.hcl, and second-boot.sh is deleted. Each
// assertion is an independent t.Run subtest so partial failures are clear.
//
// Walk/skip policy (documented; self-tested by TestHarnessScanSkipPolicy):
//   - The no-QEMU-builder scan walks test/e2e/ with filepath.WalkDir and
//     reads every non-binary, non-Go file. It skips:
//       * `.git` and `.out/` directories. .out/ holds build artifacts and
//         stale logs from the QEMU era (e.g. .out/build-prefixed.log) that are
//         gitignored and regenerated by run.sh; they are not harness content.
//       * `output-*/` and `packer_cache/` — packer build outputs, gitignored.
//       * `manifest.json` — post-processor output, gitignored.
//       * binary-ish files — a NUL byte in the first 8 KiB or invalid UTF-8
//         (raw disk fixtures, squashfs images, keys).
//       * `.go` files — test/e2e/prereq/ is Go checker infrastructure, not
//         harness content: the prereq checker must name the qemu-img
//         prerequisite. This file itself is also .go.
//   - The scan forbids QEMU-**builder** remnants only — `source "qemu"`,
//     `qemu-system`, `hashicorp/qemu`, the removed `second-boot.sh`, and
//     stale QEMU-builder documentation that references those tokens. The
//     literal `qemu-img` tool token is REQUIRED (run.sh qcow2 -> raw
//     conversion, the CheckQemuImg prerequisite checker, and the documented
//     prerequisite) and is therefore explicitly allowed ANYWHERE — run.sh,
//     README prerequisites, and template comments. Tool-package names
//     (qemu-utils) and prose that does not reference a QEMU builder (e.g.
//     "the QEMU guest") are likewise allowed. This supersedes the old strict
//     "any qemu mention" scan.
//
// The historical wording conflict — a literal `grep -rni "qemu" test/e2e/`
// returning zero matches while the required `qemu-img` string must appear — is
// resolved by explicitly permitting the qemu-img tool token, so this suite
// implements the criterion directly instead of via a compromise scan. CRLF is
// not handled: every in-scope file is plain LF text.

package e2e

import (
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"testing"
	"unicode/utf8"
)

const (
	qemuNeedle       = "qemu"           // case-insensitive anchor for builder-remnant scans
	secondBootNeedle = "second-boot.sh" // removed QEMU-era script name
)

type harnessFile struct {
	rel  string // path relative to test/e2e/, slash-separated
	data []byte
}

// repoRoot walks up from this file until it finds go.mod. This anchors every
// assertion regardless of the test runner's working directory.
func repoRoot(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller(0) failed; cannot locate repo root")
	}
	dir := filepath.Dir(thisFile)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("repo root (go.mod) not found above %s", thisFile)
		}
		dir = parent
	}
}

// mustReadRepoFile reads a file rooted at the repo root, failing the test on
// any read error so the subtest reports a clear "file missing" instead of a
// confusing comparison.
func mustReadRepoFile(t *testing.T, root, rel string) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel)))
	if err != nil {
		t.Fatalf("read %s: %v", rel, err)
	}
	return data
}

// --- no-QEMU-builder scan -------------------------------------------------

// isSkippedDir reports whether a directory is build/artifact content that must
// be excluded from the harness-content walk (see the file header).
func isSkippedDir(name string) bool {
	return name == ".git" || name == ".out" || name == "packer_cache" ||
		strings.HasPrefix(name, "output-")
}

// isSkippedFile reports whether a file is a gitignored build artifact that is
// not harness content.
func isSkippedFile(name string) bool {
	return name == "manifest.json"
}

// isGoSource excludes Go files from the scan: the prereq checker must reference
// the qemu-img prerequisite and this test file names "qemu" in its own search
// terms.
func isGoSource(name string) bool {
	return strings.HasSuffix(name, ".go")
}

// isBinary probes the first 8 KiB for a NUL byte and the full content for
// UTF-8 validity; raw disk images, squashfs fixtures and keys are skipped.
func isBinary(data []byte) bool {
	probe := data
	if len(probe) > 8192 {
		probe = probe[:8192]
	}
	if bytes.IndexByte(probe, 0) >= 0 {
		return true
	}
	return !utf8.Valid(data)
}

// findQemuViolations returns one context line per QEMU-builder remnant in data.
// The scan anchors on case-insensitive "qemu" matches and classifies each by
// its surrounding context:
//   - forbidden: the HCL builder source (`source "qemu"`, whitespace-tolerant),
//     the system emulator binary (`qemu-system...`), the plugin reference
//     (`hashicorp/qemu`), and the removed QEMU-era script `second-boot.sh`
//     (standalone name only — `assert-second-boot.sh` is the new
//     cloud-hypervisor assertion script and is allowed).
//   - allowed: the literal `qemu-img` tool token (REQUIRED by the run.sh
//     qcow2 -> raw conversion, the prereq checker, and the documented
//     prerequisite), tool-package names such as qemu-utils, and prose that
//     does not reference a QEMU builder.
//
// Go's regexp is RE2 and has no lookahead, so classification is a manual index
// scan.
func findQemuViolations(data []byte) []string {
	lower := bytes.ToLower(data)
	var out []string
	for start := 0; ; {
		i := bytes.Index(lower[start:], []byte(qemuNeedle))
		if i < 0 {
			break
		}
		pos := start + i
		start = pos + len(qemuNeedle)
		if qemuMatchForbidden(lower, pos) {
			out = append(out, contextLine(data, pos))
		}
	}
	for start := 0; ; {
		i := bytes.Index(lower[start:], []byte(secondBootNeedle))
		if i < 0 {
			return out
		}
		pos := start + i
		start = pos + len(secondBootNeedle)
		if pos > 0 && lower[pos-1] == '-' {
			continue // assert-second-boot.sh — the new CH assertion script
		}
		out = append(out, contextLine(data, pos))
	}
}

// qemuMatchForbidden classifies a single case-insensitive "qemu" occurrence at
// lower[pos] (pos points at the 'q').
func qemuMatchForbidden(lower []byte, pos int) bool {
	// The qemu-img tool token is always allowed, including in template
	// comments and README prerequisites.
	if bytes.HasPrefix(lower[pos+len(qemuNeedle):], []byte("-img")) {
		return false
	}
	// `source "qemu"` — the HCL builder source declaration. Trim trailing
	// whitespace and the quoting so `source "qemu"` and `source  "qemu"` both
	// match; prose such as "replaced the source qemu template" is also a
	// builder-remnant reference and is correctly forbidden.
	before := bytes.TrimRight(lower[:pos], " \t\"")
	if bytes.HasSuffix(before, []byte("source")) {
		return true
	}
	// qemu-system... — the QEMU system emulator binary.
	if bytes.HasPrefix(lower[pos+len(qemuNeedle):], []byte("-system")) {
		return true
	}
	// hashicorp/qemu — the QEMU plugin component reference.
	if bytes.HasSuffix(before, []byte("hashicorp/")) {
		return true
	}
	return false
}

// contextLine extracts the trimmed source line around pos for a readable
// failure message.
func contextLine(data []byte, pos int) string {
	lineStart := bytes.LastIndexByte(data[:pos], '\n') + 1
	lineEnd := len(data)
	if relEnd := bytes.IndexByte(data[pos:], '\n'); relEnd >= 0 {
		lineEnd = pos + relEnd
	}
	line := strings.TrimSpace(string(data[lineStart:lineEnd]))
	if len(line) > 140 {
		line = line[:137] + "..."
	}
	return "    " + line
}

// walkHarnessFiles walks test/e2e/ applying the documented skip policy and
// returns the in-scope text files in deterministic (WalkDir sorted) order.
func walkHarnessFiles(t *testing.T, root string) []harnessFile {
	t.Helper()
	var files []harnessFile
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if path != root && isSkippedDir(d.Name()) {
				return filepath.SkipDir
			}
			return nil
		}
		if isSkippedFile(d.Name()) || isGoSource(d.Name()) {
			return nil
		}
		data, rerr := os.ReadFile(path)
		if rerr != nil {
			return rerr
		}
		if isBinary(data) {
			return nil
		}
		rel, rerr := filepath.Rel(root, path)
		if rerr != nil {
			return rerr
		}
		files = append(files, harnessFile{rel: rel, data: data})
		return nil
	})
	if err != nil {
		t.Fatalf("walk %s: %v", root, err)
	}
	return files
}

// TestNoQemuHarnessRemnants asserts the static no-QEMU-builder criterion over
// the harness content: no QEMU-builder remnant — `source "qemu"`,
// `qemu-system`, `hashicorp/qemu`, or the removed `second-boot.sh` — in any
// in-scope file under test/e2e/. The `qemu-img` tool token and other benign
// tool/prose mentions are explicitly allowed.
func TestNoQemuHarnessRemnants(t *testing.T) {
	root := repoRoot(t)
	files := walkHarnessFiles(t, filepath.Join(root, "test", "e2e"))
	if len(files) == 0 {
		t.Fatal("scan found no in-scope files under test/e2e/; walk policy is likely wrong")
	}
	for _, f := range files {
		f := f
		t.Run(subtestName(f.rel), func(t *testing.T) {
			hits := findQemuViolations(f.data)
			if len(hits) == 0 {
				return
			}
			t.Errorf("%s contains %d QEMU-builder remnant(s):\n%s",
				f.rel, len(hits), strings.Join(hits, "\n"))
		})
	}
}

// --- template shape -------------------------------------------------------

// assertContains runs one subtest per required substring.
func assertContains(t *testing.T, file string, data []byte, wants []string) {
	t.Helper()
	for _, want := range wants {
		want := want
		t.Run("contains_"+subtestName(want), func(t *testing.T) {
			if !bytes.Contains(data, []byte(want)) {
				t.Errorf("%s must contain %q", file, want)
			}
		})
	}
}

// TestBakeTemplateContract asserts the post-migration bake template shape.
func TestBakeTemplateContract(t *testing.T) {
	root := repoRoot(t)
	data := mustReadRepoFile(t, root, "test/e2e/bake/template.pkr.hcl")
	assertContains(t, "bake/template.pkr.hcl", data, []string{
		`source "cloud-hypervisor"`,
		"firmware",
		"disk_images",
		"network_interfaces",
		`tap = "ch-tap-0"`,
		`ssh_username = "ubuntu"`,
	})
}

// TestPersistTemplateContract asserts the post-migration persist build-1
// template shape.
func TestPersistTemplateContract(t *testing.T) {
	root := repoRoot(t)
	data := mustReadRepoFile(t, root, "test/e2e/persist/template.pkr.hcl")
	assertContains(t, "persist/template.pkr.hcl", data, []string{
		`source "cloud-hypervisor"`,
		"firmware",
		"disk_images",
		"network_interfaces",
		`tap = "ch-tap-0"`,
	})
}

// TestSecondBootTemplateContract asserts the chained build-2 template exists
// as a cloud-hypervisor build whose artifact disk path is passed via -var.
func TestSecondBootTemplateContract(t *testing.T) {
	root := repoRoot(t)
	data := mustReadRepoFile(t, root, "test/e2e/persist/template-second-boot.pkr.hcl")
	assertContains(t, "persist/template-second-boot.pkr.hcl", data, []string{
		`source "cloud-hypervisor"`,
		"disk_images",
		"var.",
	})
}

// TestSecondBootScriptRemoved asserts the old QEMU second-boot script is gone;
// its logic is replaced by template-second-boot.pkr.hcl.
func TestSecondBootScriptRemoved(t *testing.T) {
	root := repoRoot(t)
	path := filepath.Join(root, "test", "e2e", "persist", "second-boot.sh")
	_, err := os.Stat(path)
	if err == nil {
		t.Error("persist/second-boot.sh must be removed; replaced by template-second-boot.pkr.hcl")
		return
	}
	if !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("stat persist/second-boot.sh: %v", err)
	}
}

// --- workflow -------------------------------------------------------------

// TestE2EWorkflowNoHostedRunners asserts the e2e workflow has no hosted runner
// image and no scheduled trigger.
func TestE2EWorkflowNoHostedRunners(t *testing.T) {
	root := repoRoot(t)
	data := mustReadRepoFile(t, root, ".github/workflows/e2e.yml")
	lower := bytes.ToLower(data)
	for _, forbidden := range []string{"ubuntu-latest", "schedule:"} {
		forbidden := forbidden
		t.Run("no_"+subtestName(forbidden), func(t *testing.T) {
			if bytes.Contains(lower, []byte(forbidden)) {
				t.Errorf(".github/workflows/e2e.yml must not contain %q", forbidden)
			}
		})
	}
}

// --- make e2e executability ----------------------------------------------

// TestHarnessScriptsExecutable asserts run.sh scripts exist and carry an
// execute bit so `make e2e` can invoke them.
func TestHarnessScriptsExecutable(t *testing.T) {
	root := repoRoot(t)
	for _, rel := range []string{"bake/run.sh", "persist/run.sh"} {
		rel := rel
		t.Run(subtestName(rel), func(t *testing.T) {
			path := filepath.Join(root, "test", "e2e", filepath.FromSlash(rel))
			info, err := os.Stat(path)
			if err != nil {
				t.Fatalf("stat %s: %v (make e2e needs it)", rel, err)
			}
			if info.Mode()&0o111 == 0 {
				t.Errorf("%s must be executable (mode&0111 != 0) for make e2e; got %v", rel, info.Mode())
			}
		})
	}
}

// --- skip-policy self-tests (documentation of the walk contract) ----------

// TestHarnessScanSkipPolicy locks in the documented skip policy so the walk
// cannot silently start scanning build artifacts or binary fixtures.
func TestHarnessScanSkipPolicy(t *testing.T) {
	for _, tt := range []struct {
		name string
		want bool
	}{
		{name: ".git", want: true},
		{name: ".out", want: true},
		{name: "output-persist-golden", want: true},
		{name: "packer_cache", want: true},
		{name: "bake", want: false},
		{name: "persist", want: false},
		{name: "fixtures", want: false},
		{name: "prereq", want: false},
	} {
		tt := tt
		t.Run("dir_"+subtestName(tt.name), func(t *testing.T) {
			if got := isSkippedDir(tt.name); got != tt.want {
				t.Errorf("isSkippedDir(%q) = %v, want %v", tt.name, got, tt.want)
			}
		})
	}
	for _, tt := range []struct {
		name string
		want bool
	}{
		{name: "manifest.json", want: true},
		{name: "template.pkr.hcl", want: false},
		{name: "run.sh", want: false},
	} {
		tt := tt
		t.Run("file_"+subtestName(tt.name), func(t *testing.T) {
			if got := isSkippedFile(tt.name); got != tt.want {
				t.Errorf("isSkippedFile(%q) = %v, want %v", tt.name, got, tt.want)
			}
		})
	}
	for _, tt := range []struct {
		name string
		want bool
	}{
		{name: "prereq.go", want: true},
		{name: "harness_test.go", want: true},
		{name: "run.sh", want: false},
		{name: "template.pkr.hcl", want: false},
	} {
		tt := tt
		t.Run("go_"+subtestName(tt.name), func(t *testing.T) {
			if got := isGoSource(tt.name); got != tt.want {
				t.Errorf("isGoSource(%q) = %v, want %v", tt.name, got, tt.want)
			}
		})
	}
	for _, tt := range []struct {
		name string
		data []byte
		want bool
	}{
		{name: "nul_byte", data: []byte{'a', 0, 'b'}, want: true},
		{name: "invalid_utf8", data: []byte{0xff, 0xfe, 0xfd}, want: true},
		{name: "plain_text", data: []byte("hello qemu\n"), want: false},
	} {
		tt := tt
		t.Run("binary_"+tt.name, func(t *testing.T) {
			if got := isBinary(tt.data); got != tt.want {
				t.Errorf("isBinary(%q) = %v, want %v", tt.name, got, tt.want)
			}
		})
	}
	for _, tt := range []struct {
		name string
		data []byte
		want int // expected number of QEMU-builder-remnant violations
	}{
		{name: "tool_token_run_sh", data: []byte("qemu-img convert -O raw"), want: 0},
		{name: "tool_token_template_comment", data: []byte("# boot disk converted with qemu-img"), want: 0},
		{name: "tool_package_name", data: []byte("package qemu-utils"), want: 0},
		{name: "prose_guest", data: []byte("Runs inside the QEMU guest"), want: 0},
		{name: "builder_source", data: []byte("source \"qemu\" \"bake\" {"), want: 1},
		{name: "builder_source_double_space", data: []byte("source  \"qemu\" {"), want: 1},
		{name: "qemu_system_binary", data: []byte("qemu-system-x86_64 -m 2G"), want: 1},
		{name: "hashicorp_plugin", data: []byte("source = \"github.com/hashicorp/qemu\""), want: 1},
		{name: "removed_script", data: []byte("run ./second-boot.sh"), want: 1},
		{name: "new_assert_script", data: []byte("runs assert-second-boot.sh"), want: 0},
	} {
		tt := tt
		t.Run("scan_"+subtestName(tt.name), func(t *testing.T) {
			hits := findQemuViolations(tt.data)
			if len(hits) != tt.want {
				t.Errorf("findQemuViolations(%q) = %d hit(s), want %d:\n%s",
					tt.data, len(hits), tt.want, strings.Join(hits, "\n"))
			}
		})
	}
}

// --- seed instance freshness + bake setcap parity --------------------------

// seedInstanceIDTimestampToken matches a `date +%s`-style per-run timestamp
// token (e.g. `$(date +%s)` or `$(date +%s%N)`), the evidence that a harness
// generates a unique NoCloud instance-id per run instead of reusing the
// constant id cloud-init cached on a previously booted raw disk.
var seedInstanceIDTimestampToken = regexp.MustCompile(`date[^\n]*\+%s`)

// seedInstanceIDInterpolation matches an `instance-id: ${VAR}` meta-data
// line, the alternative acceptable form where a variable carries the per-run
// id into the heredoc.
var seedInstanceIDInterpolation = regexp.MustCompile(`instance-id:\s*\$\{[A-Za-z_][A-Za-z0-9_]*\}`)

// TestHarnessSeedInstanceFreshness asserts both harness runners generate a
// per-run unique NoCloud instance-id. A constant instance-id (e.g.
// `instance-id: packer-bake-e2e`) makes cloud-init treat a reused writable
// raw disk as the SAME instance (new=False) and never re-apply the seed
// network-config, so the guest never gets the 10.0.2.2 / 192.168.249.2
// address the packer SSH communicator needs. Each file and each assertion is
// an independent t.Run subtest so partial failures are clear.
func TestHarnessSeedInstanceFreshness(t *testing.T) {
	root := repoRoot(t)
	for _, rel := range []string{"bake/run.sh", "persist/run.sh"} {
		rel := rel
		data := mustReadRepoFile(t, root, "test/e2e/"+rel)
		t.Run(subtestName(rel)+"_unique_instance_id", func(t *testing.T) {
			if !seedInstanceIDTimestampToken.Match(data) && !seedInstanceIDInterpolation.Match(data) {
				t.Errorf("%s must generate a per-run unique NoCloud instance-id: a `date +%%s`-style token or an instance-id variable interpolation into meta-data", rel)
			}
		})
		t.Run(subtestName(rel)+"_no_constant_instance_id", func(t *testing.T) {
			// Compare whole trimmed lines, not substrings: the fixed unique
			// form `instance-id: packer-bake-e2e-$(date +%s)` legitimately
			// contains the constant as a prefix and must not be flagged.
			constants := []string{
				"instance-id: packer-bake-e2e",
				"instance-id: packer-persist-e2e",
			}
			for _, line := range bytes.Split(data, []byte("\n")) {
				trimmed := string(bytes.TrimSpace(line))
				for _, c := range constants {
					if trimmed == c {
						t.Errorf("%s must not hardcode the constant instance-id %q (a per-run unique id is required)", rel, c)
					}
				}
			}
		})
	}
}

// TestBakeRunShSetcapParity asserts the bake harness grants cloud-hypervisor
// CAP_NET_ADMIN so it can attach the pre-created TAP (TUNSETIFF) on a fresh
// host, mirroring the conditional setcap block in test/e2e/persist/run.sh.
func TestBakeRunShSetcapParity(t *testing.T) {
	root := repoRoot(t)
	data := mustReadRepoFile(t, root, "test/e2e/bake/run.sh")
	assertContains(t, "bake/run.sh", data, []string{"setcap cap_net_admin+ep"})
}

// subtestName turns an arbitrary string into a flat, stable t.Run name.
func subtestName(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}
